print "CREATE TABLE IF NOT EXISTS movie (id INTEGER PRIMARY KEY  AUTOINCREMENT, title VARCHAR DEFAULT NULL, year VARCHAR DEFAULT NULL, rated VARCHAR DEFAULT NULL, released VARCHAR DEFAULT NULL, genre VARCHAR DEFAULT NULL, director VARCHAR DEFAULT NULL, writer VARCHAR DEFAULT NULL, actors VARCHAR DEFAULT NULL, plot VARCHAR DEFAULT NULL, poster VARCHAR DEFAULT NULL, runtime VARCHAR DEFAULT NULL, rating VARCHAR DEFAULT NULL, votes VARCHAR DEFAULT NULL, imdb VARCHAR DEFAULT NULL, tstamp VARCHAR DEFAULT NULL);\n" ;
while(<>){ 
 my $cmd = "perl getMovieData.pl \"$_\""; 
 system($cmd);
}
